version: '3'
services:

  backend:
    image: '322456/signalonebackend:dev'
    ports:
      - 8080:8080
    depends_on:
      - solutions-agent
      - mongo-db
    volumes:
      - .:/app

  solutions-agent:
      image: '322456/solutions-agent:dev'
      ports:
        - 8081:8081
      
  mongo-db:
      container_name: mongo-db
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - ./mongo-data:/data/db
