// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/containers": {
            "get": {
                "description": "Get a list of containers based on the provided user ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Get a list of containers based on the provided user ID.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to filter containers",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/issues": {
            "get": {
                "description": "Search for issues based on specified criteria.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "issues"
                ],
                "summary": "Search for issues based on specified criteria.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset for paginated results",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of results per page (default: 30, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search string for filtering issues",
                        "name": "searchString",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by container name",
                        "name": "container",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by issue severity",
                        "name": "issueSeverity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by issue type",
                        "name": "issueType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter issues starting from this timestamp (RFC3339 format)",
                        "name": "startTimestamp",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter issues until this timestamp (RFC3339 format)",
                        "name": "endTimestamp",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter resolved or unresolved issues",
                        "name": "isResolved",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete issues based on the provided container name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "issues"
                ],
                "summary": "Delete issues based on the provided container name.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container name to delete issues from",
                        "name": "container",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/issues/analysis": {
            "put": {
                "description": "Perform log analysis based on the provided logs and generate solutions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analysis"
                ],
                "summary": "Perform log analysis and generate solutions.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003ctoken\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Log analysis payload",
                        "name": "logAnalysisPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LogAnalysisPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/issues/resolve/{id}": {
            "post": {
                "description": "Resolve an issue by providing its ID and updating its status to resolved.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "issues"
                ],
                "summary": "Resolve an issue by setting its status to resolved.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the issue to be resolved",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/issues/{id}": {
            "get": {
                "description": "Get information about a specific issue by providing its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "issues"
                ],
                "summary": "Get information about a specific issue.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the issue",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Issue"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.LogAnalysisPayload": {
            "type": "object",
            "properties": {
                "containerName": {
                    "type": "string"
                },
                "logs": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "models.Issue": {
            "type": "object",
            "properties": {
                "containerName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isResolved": {
                    "type": "boolean"
                },
                "issuePredictedSolutionsSources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IssueSolutionPredictionSolutionSource"
                    }
                },
                "logSummary": {
                    "type": "string"
                },
                "logs": {
                    "type": "string"
                },
                "predictedSolutionsSummary": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "models.IssueSolutionPredictionSolutionSource": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "SignalOne API",
	Description:      "API for SignalOne application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
